name: Merge queue # Adopted from tay1orjones
on:
  pull_request_target:
    types: [labeled, opened, reopened]

jobs:
  add-to-merge-queue:
    name: Add to queue when automerge label is present
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Log github event
        env:
          $GITHUB_CONTEXT_LABELS:
            ${{ toJson(github.event.pull_request.labels) }}
        run: echo "$GITHUB_CONTEXT_LABELS"
      - name: 'Add the PR to the merge queue via the GitHub CLI'
        if:
          ${{ contains(github.event.pull_request.labels.*.name,
          format('status{0} ready to merge 🎉', ':'))}}
        run: gh pr merge "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{github.event.pull_request.html_url}}
